### ISSUE TITLE
Support undo/redo in editor

### ISSUE THREAD

**Issue by mwrynn** [rogerboesch/vectrex-dev#7]
The Edit menu as well as cmd-z/cmd-shift-z should undo/redo respectively. It is difficult to work with any editor these days without undo/redo.

**Comment by rogerboesch** [comment]
Yes I agree, the editor needs much improvment, it's very basic. I work already on that and especially undo/redo will be soon available.

**Comment by rogerboesch** [comment]
It's implemented, will be available in next reelase

**Comment by rogerboesch** [comment]
Undo and Redo is now available as latest version (1.0.8)
